### ISSUE TITLE
네이버 웹 로그인 cors 이슈

### ISSUE THREAD

**Issue by nain93** [bsideproject/Moa-app#13]
네이버 웹 로그인이 `cors` 에러를 띄움
해결법은 프론트에서 `https://nid.naver.com/` 에 proxy 처리를 해주거나 

서버에서 요청을하고 프론트로 응답을 전달 해주는 방법 `client_id` 와 `redirect_uri` 을 서버로 전달해줘야함 
이 경우 네이버 웹 로그인만을 위한 `api`가 추가되어야함

**Comment by paulracooni** [comment]
현재 이거 작업 중이에요.

**Comment by paulracooni** [comment]
Django 활용, 인증 Proxy 서버 만들어 웹 로그인 진행 절차 해결되었고
옛날 코드 레포지토리에서 작업해서, 현재 최신 코드 위에서 옮겨적은 후 PR 날리도록 하겠습니다.
