### ISSUE TITLE
flutter web에서 특정 url로 접속시 '/' 으로 넘어가는 이슈

### ISSUE THREAD

**Issue by nain93** [bsideproject/moa-app#36]
flutter web에서 url을 주소창에 입력시 아래 에러 발생하면서 '/' 홈으로 리다이렉트 됩니다
공유 링크를 받을때 `http://localhost:8080/content/0` 같은 식의 링크가 되고 이 링크를 열었을때  해당 취향 컨텐츠로 이동해야되나 홈으로 리다이렉트 됩니다
<img width="633" alt="스크린샷 2023-07-05 오후 3 45 39" src="https://github.com/bsideproject/moa-app/assets/73378472/92659f91-d362-4e3e-b3c3-70cf1d4ca761">

현재 `usePathUrlStrategy()` 을 사용해서 에러가 발생하고 리다이렉트가 되고있습니다
궁극적으로 `usePathUrlStrategy()` 을 사용하면서 리다이렉트 문제를 해결해야합니다

### 변경사항
현재 취향 아이템 상세정보를 볼때 `id` 정보를 위젯으로 내려주는데 `url`로 바로 접속할 경우를 대비해서 웹일 경우는 `url`에서 가져오는 방식으로 변경필요

**Comment by paulracooni** [comment]
이거 API 연동 하면서 이문제도 같이 잡아 볼게요.

**Comment by nain93** [comment]
@paulracooni 요거 제가할게요 원인알았어요
